#Database Configuration
dbMethod: sqlite #sqlite or mysql

#MySQL Configuration
mysql: 
    host: 
    user: 
    pass: 
    port: 
    db_name: 

#SQLite Configuration
sqlite: 
    db_name: economyplus.db

#Plugin configuration
basic: 
    bankname: EconomyPlus
    moneyname: PO
    lang: en
    moneyonfirstlogin: 50
    encoding: UTF-8
#Signs (You can color your texts with color codes Ex:&a)
signs:
    line1color: '&a'
    put:
        detector: put
        line2: 'Put money'
        line3: null
        line4: null
    take:
        detector: take
        line2: 'Get money'
        line3: null
        line4: null
    see:
        detector: see
        line2: 'See money'
        line3: null
        line4: null

        